### ISSUE TITLE
Creation and edition for teachers

### ISSUE THREAD

**Issue by combefis** [combefis/ECM#2]
A teacher must not be able to list all the courses nor create a new one, and cannot create a new exam, nor list all the exams.

**Comment by AlexisTM** [comment]
There is two places for the rights : 
- The client's menu <= Still visible... The rights for the main menu (courses) are for all the rights of the submenus (New course, List courses)
- The server route <= Now correct, if the user come to the page, he won't have data.

**Comment by AlexisTM** [comment]
According to the [documentation](http://meanjs.org/docs.html#menus), there is a missing parameter..

Menus.addSubMenuItem(menuId, rootMenuItemURL, menuItemTitle, menuItemURL, [menuItemUIRoute], [isPublic], [roles]);

[menuItemUIRoute] : default menuItemURL.

That's why we just have to add the menuItemURL a second time.
